version: '3'
services:
    web:
        image: ungastos
        command: > 
            sh -c "./scripts/setup.sh &&
                   python3 UnGastos/manage.py runserver 0.0.0.0:8000"
        build: 
          context: .
          dockerfile: Dockerfile
        ports:
          - 8000:8000
        volumes:
          - ./:/code
    test:
        image: ungastos
        command: >
            sh -c "./scripts/setup.sh &&
                   python3 UnGastos/manage.py test"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - 8000:8000
        volumes:
          - ./:/code
